export const paisesUE = {
    "alemania": "DE",
    "austria": "AT",
    "belgica": "BE",
    "bulgaria": "BG",
    "chipre": "CY",
    "croacia": "HR",
    "dinamarca": "DK",
    "eslovaquia": "SK",
    "eslovenia": "SI",
    "espana": "ES",
    "estonia": "EE",
    "finlandia": "FI",
    "francia": "FR",
    "grecia": "GR",
    "hungria": "HU",
    "irlanda": "IE",
    "italia": "IT",
    "letonia": "LV",
    "lituania": "LT",
    "luxemburgo": "LU",
    "malta": "MT",
    "paises bajos": "NL",
    "polonia": "PL",
    "portugal": "PT",
    "republica checa": "CZ",
    "rumania": "RO",
    "suecia": "SE"
};